docker run -d --name rcmail136_php56 \
    -p 8443:443 \
    -e PHP_MEMORY_LIMIT=64M \
    -e MAX_UPLOAD=100M \
    -e PHP_MAX_FILE_UPLOAD=40 \
    -e PHP_MAX_POST=101M \
    -e FPM_MAX_CHILDREN=40 \
    -e FPM_START_SERVERS=4 \
    -e FPM_MIN_SPARE_SERVERS=3 \
    -e FPM_MAX_SPARE_SERVERS=20 \
    -v /home/roundcube/config:/home/roundcube/config \
    -v /home/roundcube/logs:/home/roundcube/logs \
    --restart unless-stopped rcmail/rcmail:devel_php56
